### ISSUE TITLE
Using Vlc's gpu acceleration 

### ISSUE THREAD

**Issue by lshkiller** [RSATom/WebChimera#85] opened 2015-03-04 18:47 UTC
Hi,

Is it possible to enable vlc's feature of GPU Acceleration?

Thanks

**Comment by RSATom** [comment] 2015-03-05 03:50
In current version gpu acceleration was disabled since it's not clear how to enable it in Vlc 2.1.x.

**Comment by lshkiller** [comment] 2015-03-08 09:42
WebChimera is compiled to Vlc 2.1.x ?
Because I think that in Vlc 2.2.0 gpu is enabled

**Comment by RSATom** [comment] 2015-03-08 14:36
this time it uses Vlc 2.1.5, I don't want use Vlc 2.2 until at least Vlc 2.2.1 will out (I just think there will me some bugs, which should be fixed in 2.2.1)

**Comment by fapeci** [comment] 2015-03-08 22:19
I think that vlc 2.2.0 first nightly is dating back as early as July 8th 2013, so the current stable release 2.2.0 should be pretty much bug free
http://nightlies.videolan.org/build/win32/backup/vlc-2.2.0-20130708-0030/
Not to mention that vlc 3.0.0 works much faster in opening the streams etc.

**Comment by RSATom** [comment] 2015-03-09 04:02
The problem is while some OpenSource product not released, not so many people try to use it, so most of the bugs appears only after public release.

**Comment by RSATom** [comment] 2015-03-09 04:06
> GPU Acceleration is enabled by the following option: --ffmpeg-hw or --avcodec-hw=any
I'm curious, if it will work if I will pass both options to libvlc simultaneously?

**Comment by fapeci** [comment] 2015-03-09 09:24
I guess leaving it as a API call from Player would be an appropriate as is the situation with other options.

**Comment by RSATom** [comment] 2015-03-09 09:50
yes, we already have "hw-accel" startup option. The question is should I add both `--ffmpeg-hw --avcodec-hw=any` if  `hw-accel=true` or only one of them (and add another startup option for second)?

**Comment by fapeci** [comment] 2015-03-09 11:38
I would say since `--avcodec-hw` have many input parameters dependent on platforms and graphics card vendor, it should be an optional parameter separate from the first one i.e. `--ffmpeg-hw`.

**Comment by RSATom** [comment] 2015-03-09 11:53
`--avcodec-hw=any` - will not work always?

**Comment by fapeci** [comment] 2015-03-09 11:56
Yes, that's right. On intel hd graphics cards doesn't work.

**Comment by RSATom** [comment] 2015-03-09 11:57
Ok, this time I've made them both enabled, If we will meet some issues with it I'll create separate startup option for `avcodec-hw`.

**Comment by RSATom** [comment] 2015-03-09 11:58
Now I think this issue could be closed...

**Closed by RSATom** 2015-03-09 11:58 UTC
Labels: enhancement
